/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mysqlcon;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class StartPage extends javax.swing.JFrame {
    
    String uid = "root";
    String pwd = "root";

    /**
     * Creates new form StartPage
     */
    public StartPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cust_detail = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        allValues = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        acctno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        del_acctno = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        loans = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        allValues1 = new javax.swing.JTable();
        address1 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        acctno1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        del_acctno1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        phone1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        allvalues = new javax.swing.JFrame();
        name2 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        allValues2 = new javax.swing.JTable();
        del_acctno2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        address2 = new javax.swing.JTextField();
        phone2 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        acctno2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        branches = new javax.swing.JFrame();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        acctno3 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        allValues3 = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        del_acctno3 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        phone3 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        name3 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();

        cust_detail.setMinimumSize(new java.awt.Dimension(700, 510));

        allValues.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Acct No", "Name", "Phone", "Address"
            }
        ));
        jScrollPane1.setViewportView(allValues);

        jButton6.setText("Get All Values");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel5.setText("AcctNo:");

        jLabel6.setText("Name:");

        jLabel7.setText("Phone:");

        jLabel8.setText("Address:");

        jButton7.setText("Insert Row");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel9.setText("AcctNo:");

        del_acctno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_acctnoActionPerformed(evt);
            }
        });

        jButton8.setText("Delete Row");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cust_detailLayout = new javax.swing.GroupLayout(cust_detail.getContentPane());
        cust_detail.getContentPane().setLayout(cust_detailLayout);
        cust_detailLayout.setHorizontalGroup(
            cust_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cust_detailLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(cust_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cust_detailLayout.createSequentialGroup()
                        .addGroup(cust_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cust_detailLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(42, 42, 42))
                            .addGroup(cust_detailLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(cust_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acctno, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(del_acctno, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(cust_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cust_detailLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(42, 42, 42))
                            .addGroup(cust_detailLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(30, 30, 30)))
                        .addGroup(cust_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(address)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(cust_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        cust_detailLayout.setVerticalGroup(
            cust_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cust_detailLayout.createSequentialGroup()
                .addGroup(cust_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cust_detailLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jButton6))
                    .addGroup(cust_detailLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(cust_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cust_detailLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(cust_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(acctno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(cust_detailLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jButton7)))
                .addGap(12, 12, 12)
                .addGroup(cust_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addGroup(cust_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(del_acctno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        loans.setMinimumSize(new java.awt.Dimension(700, 510));

        allValues1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Acct No", "Type", "Interest", "Amount"
            }
        ));
        jScrollPane2.setViewportView(allValues1);
        if (allValues1.getColumnModel().getColumnCount() > 0) {
            allValues1.getColumnModel().getColumn(3).setHeaderValue("Branch");
        }

        jButton9.setText("Insert Row");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Get All Values");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel10.setText("AcctNo:");

        jLabel11.setText("Type:");

        jButton11.setText("Delete Row");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel12.setText("AcctNo:");

        del_acctno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_acctno1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Interest:");

        jLabel14.setText("Amount:");

        javax.swing.GroupLayout loansLayout = new javax.swing.GroupLayout(loans.getContentPane());
        loans.getContentPane().setLayout(loansLayout);
        loansLayout.setHorizontalGroup(
            loansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loansLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(loansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loansLayout.createSequentialGroup()
                        .addGroup(loansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loansLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(42, 42, 42))
                            .addGroup(loansLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(loansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phone1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acctno1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(del_acctno1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(loansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loansLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(42, 42, 42))
                            .addGroup(loansLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(30, 30, 30)))
                        .addGroup(loansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(name1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(address1)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(loansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        loansLayout.setVerticalGroup(
            loansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loansLayout.createSequentialGroup()
                .addGroup(loansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loansLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jButton10))
                    .addGroup(loansLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(loansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loansLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(loansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(acctno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(loansLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jButton9)))
                .addGap(12, 12, 12)
                .addGroup(loansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(phone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(address1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addGroup(loansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(del_acctno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        allvalues.setMinimumSize(new java.awt.Dimension(700, 510));

        jButton12.setText("Delete Row");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel15.setText("AcctNo:");

        allValues2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Acct No", "Name", "Balance", "Branch"
            }
        ));
        jScrollPane3.setViewportView(allValues2);
        if (allValues2.getColumnModel().getColumnCount() > 0) {
            allValues2.getColumnModel().getColumn(3).setHeaderValue("Branch");
        }

        del_acctno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_acctno2ActionPerformed(evt);
            }
        });

        jLabel16.setText("Balance:");

        jButton13.setText("Insert Row");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel17.setText("Branch:");

        jButton14.setText("Get All Values");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel18.setText("AcctNo:");

        jLabel19.setText("Name:");

        javax.swing.GroupLayout allvaluesLayout = new javax.swing.GroupLayout(allvalues.getContentPane());
        allvalues.getContentPane().setLayout(allvaluesLayout);
        allvaluesLayout.setHorizontalGroup(
            allvaluesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allvaluesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(allvaluesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(allvaluesLayout.createSequentialGroup()
                        .addGroup(allvaluesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, allvaluesLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(42, 42, 42))
                            .addGroup(allvaluesLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(allvaluesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phone2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acctno2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(del_acctno2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(allvaluesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, allvaluesLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(42, 42, 42))
                            .addGroup(allvaluesLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(30, 30, 30)))
                        .addGroup(allvaluesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(name2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(address2)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(allvaluesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        allvaluesLayout.setVerticalGroup(
            allvaluesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allvaluesLayout.createSequentialGroup()
                .addGroup(allvaluesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(allvaluesLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jButton14))
                    .addGroup(allvaluesLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(allvaluesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(allvaluesLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(allvaluesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(acctno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(allvaluesLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jButton13)))
                .addGap(12, 12, 12)
                .addGroup(allvaluesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(phone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(address2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addGroup(allvaluesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(del_acctno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        branches.setMinimumSize(new java.awt.Dimension(700, 510));

        jLabel20.setText("Branch No:");

        jLabel21.setText("Branch No:");

        allValues3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Branch No.", "Branch", "Location"
            }
        ));
        jScrollPane4.setViewportView(allValues3);

        jLabel22.setText("Branch:");

        del_acctno3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_acctno3ActionPerformed(evt);
            }
        });

        jLabel23.setText("Location:");

        jButton15.setText("Insert Row");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("Get All Values");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("Delete Row");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout branchesLayout = new javax.swing.GroupLayout(branches.getContentPane());
        branches.getContentPane().setLayout(branchesLayout);
        branchesLayout.setHorizontalGroup(
            branchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(branchesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(branchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(branchesLayout.createSequentialGroup()
                        .addGroup(branchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, branchesLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(42, 42, 42))
                            .addGroup(branchesLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(branchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phone3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acctno3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(del_acctno3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(jLabel22)
                        .addGap(42, 42, 42)
                        .addComponent(name3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(branchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        branchesLayout.setVerticalGroup(
            branchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(branchesLayout.createSequentialGroup()
                .addGroup(branchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(branchesLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jButton16))
                    .addGroup(branchesLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(branchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(branchesLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(branchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(acctno3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(name3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(branchesLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jButton15)))
                .addGap(12, 12, 12)
                .addGroup(branchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(phone3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addGroup(branchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(del_acctno3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Customer Detail");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("All accounts");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Loan Accounts");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Bank Branches");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Database:");

        jTextField1.setText("vikendu");

        jLabel2.setText("Username:");

        jTextField2.setText("root");

        jLabel3.setText("Password:");

        jPasswordField1.setText("root");

        jLabel4.setText("Port No:");

        jTextField3.setText("3306");

        jButton5.setText("Get Connection");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel24.setText("Bank Management System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addComponent(jTextField2)
                                    .addComponent(jPasswordField1)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton5)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextField3))))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(45, 45, 45)
                .addComponent(jButton5)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        allvalues.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel)allValues.getModel();

        for( int i = model.getRowCount() - 1; i >= 0; i-- ) //Empty table
        {
            model.removeRow(i);
        }

        try{
            //System.out.println("Yup");
            Class.forName("com.mysql.cj.jdbc.Driver");
            //System.out.println("Yup");
            String uid= "root";
            String pwd = "root";
            String compu="jdbc:mysql://localhost:3306/vikendu";
            Connection con = DriverManager.getConnection(compu,uid,pwd);
            // System.out.println("Yup");
            Statement stmt = con.createStatement();
            String query ="SELECT * from cust_detail;";
            ResultSet rs = stmt.executeQuery(query);
            //System.out.println("Yup");

            while(rs.next())
            {
                String acct_no = rs.getString ("acctno");
                String name = rs.getString("name");
                String phone =rs.getString("phone");
                String city = rs.getString("address");

                model.addRow( new Object[] {acct_no, name, phone,city});

            }

            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Database Disconnected or KEY Conflict.");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        cust_detail.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    int acct_no= Integer.parseInt(acctno.getText());
    String name_= name.getText();
    int phone_no= Integer.parseInt(phone.getText());
    String city= address.getText();
               
if(acct_no == 0||name_.equals("")||city.equals(""))
{
    JOptionPane.showMessageDialog(null,"One or more entry is empty!");

}

else{
try{
    Class.forName("com.mysql.cj.jdbc.Driver");
    String compu="jdbc:mysql://localhost:3306/vikendu";
    Connection con = DriverManager.getConnection(compu,uid,pwd);
    Statement stmt = con.createStatement();
    String query = "insert into cust_detail values("+acct_no+",'"+name_+"',"+phone_no+",'"+city+"');";
    stmt.executeUpdate(query);

    JOptionPane.showMessageDialog(null,"Updated");

    stmt.close();
    con.close();

}
catch(Exception e) {
    JOptionPane.showMessageDialog(null,"Database Disconnected or KEY Conflict.");
}
}
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void del_acctnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_acctnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_del_acctnoActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        int acct_no = Integer.parseInt(del_acctno.getText());
        try{
    Class.forName("com.mysql.cj.jdbc.Driver");
    //System.out.println("Yup");
    String compu="jdbc:mysql://localhost:3306/vikendu";
    Connection con = DriverManager.getConnection(compu,uid,pwd);
   // System.out.println("Yup");
    Statement stmt = con.createStatement();
    String query = "delete from cust_detail where acctno ="+acct_no+";";
    stmt.executeUpdate(query);

    JOptionPane.showMessageDialog(null,"Updated");

    stmt.close();
    con.close();

}
catch(Exception e) {
    JOptionPane.showMessageDialog(null,"Database Disconnected or KEY Conflict.");
}
    
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
            
 int acct_no= Integer.parseInt(acctno1.getText());
    String name_= name1.getText();
    int phone_no= Integer.parseInt(phone1.getText());
    String city= address1.getText();
               
if(acct_no == 0||name_.equals("")||city.equals(""))
{
    JOptionPane.showMessageDialog(null,"One or more entry is empty!");

}

else{
try{
    Class.forName("com.mysql.cj.jdbc.Driver");
    String compu="jdbc:mysql://localhost:3306/vikendu";
    Connection con = DriverManager.getConnection(compu,uid,pwd);
    Statement stmt = con.createStatement();
    String query = "insert into loans values("+acct_no+",'"+name_+"',"+phone_no+",'"+city+"');";
    stmt.executeUpdate(query);

    JOptionPane.showMessageDialog(null,"Updated");

    stmt.close();
    con.close();

}
catch(Exception e) {
    JOptionPane.showMessageDialog(null,"Database Disconnected or KEY Conflict.");
}
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
         DefaultTableModel model = (DefaultTableModel)allValues1.getModel();

        for( int i = model.getRowCount() - 1; i >= 0; i-- ) //Empty table
        {
            model.removeRow(i);
        }

        try{
            //System.out.println("Yup");
            Class.forName("com.mysql.cj.jdbc.Driver");
            //System.out.println("Yup");
            String compu="jdbc:mysql://localhost:3306/vikendu";
            Connection con = DriverManager.getConnection(compu,uid,pwd);
            // System.out.println("Yup");
            Statement stmt = con.createStatement();
            String query ="SELECT * from loans;";
            ResultSet rs = stmt.executeQuery(query);
            //System.out.println("Yup");

            while(rs.next())
            {
                String acct_no = rs.getString ("acctno");
                String name = rs.getString("type");
                String phone =rs.getString("interest");
                String city = rs.getString("amount");

                model.addRow( new Object[] {acct_no, name, phone,city});

            }

            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Database Disconnected or KEY Conflict.");
        }
                                    
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        
        int acct_no = Integer.parseInt(del_acctno1.getText());
        try{
    Class.forName("com.mysql.cj.jdbc.Driver");
    //System.out.println("Yup");
    String compu="jdbc:mysql://localhost:3306/vikendu";
    Connection con = DriverManager.getConnection(compu,uid,pwd);
   // System.out.println("Yup");
    Statement stmt = con.createStatement();
    String query = "delete from loans where acctno ="+acct_no+";";
    stmt.executeUpdate(query);

    JOptionPane.showMessageDialog(null,"Updated");

    stmt.close();
    con.close();

}
catch(Exception e) {
    JOptionPane.showMessageDialog(null,"Database Disconnected or KEY Conflict.");
}


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void del_acctno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_acctno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_del_acctno1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 
        loans.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        
        int acct_no = Integer.parseInt(del_acctno2.getText());
        try{
    Class.forName("com.mysql.cj.jdbc.Driver");
    //System.out.println("Yup");
    String compu="jdbc:mysql://localhost:3306/vikendu";
    Connection con = DriverManager.getConnection(compu,uid,pwd);
   // System.out.println("Yup");
    Statement stmt = con.createStatement();
    String query = "delete from all_acct where acctno ="+acct_no+";";
    stmt.executeUpdate(query);

    JOptionPane.showMessageDialog(null,"Updated");

    stmt.close();
    con.close();

}
catch(Exception e) {
    JOptionPane.showMessageDialog(null,"Database Disconnected or KEY Conflict.");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void del_acctno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_acctno2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_del_acctno2ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        int acct_no= Integer.parseInt(acctno2.getText());
    String name_= name2.getText();
    int phone_no= Integer.parseInt(phone2.getText());
    String city= address2.getText();
               
if(acct_no == 0||name_.equals("")||city.equals(""))
{
    JOptionPane.showMessageDialog(null,"One or more entry is empty!");

}

else{
try{
    Class.forName("com.mysql.cj.jdbc.Driver");
    String compu="jdbc:mysql://localhost:3306/vikendu";
    Connection con = DriverManager.getConnection(compu,uid,pwd);
    Statement stmt = con.createStatement();
    String query = "insert into all_acct values("+acct_no+",'"+name_+"',"+phone_no+",'"+city+"');";
    stmt.executeUpdate(query);

    JOptionPane.showMessageDialog(null,"Updated");

    stmt.close();
    con.close();

}
catch(Exception e) {
    JOptionPane.showMessageDialog(null,"Database Disconnected or KEY Conflict.");
}
}
        

            // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        DefaultTableModel model = (DefaultTableModel)allValues2.getModel();

        for( int i = model.getRowCount() - 1; i >= 0; i-- ) //Empty table
        {
            model.removeRow(i);
        }

        try{
            //System.out.println("Yup");
            Class.forName("com.mysql.cj.jdbc.Driver");
            //System.out.println("Yup");
            String compu="jdbc:mysql://localhost:3306/vikendu";
            Connection con = DriverManager.getConnection(compu,uid,pwd);
            // System.out.println("Yup");
            Statement stmt = con.createStatement();
            String query ="SELECT * from all_acct;";
            ResultSet rs = stmt.executeQuery(query);
            //System.out.println("Yup");

            while(rs.next())
            {
                String acct_no = rs.getString ("acctno");
                String name = rs.getString("name");
                String phone =rs.getString("balance");
                String city = rs.getString("branch");

                model.addRow( new Object[] {acct_no, name, phone,city});

            }

            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Database Disconnected or KEY Conflict.");
        }
            
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void del_acctno3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_acctno3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_del_acctno3ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        
        int acct_no= Integer.parseInt(acctno3.getText());
    String name_= name3.getText();
    String city= phone3.getText();
               
if(acct_no == 0||name_.equals("")||city.equals(""))
{
    JOptionPane.showMessageDialog(null,"One or more entry is empty!");

}

else{
try{
    Class.forName("com.mysql.cj.jdbc.Driver");
    String compu="jdbc:mysql://localhost:3306/vikendu";
    Connection con = DriverManager.getConnection(compu,uid,pwd);
    Statement stmt = con.createStatement();
    String query = "insert into branches values("+acct_no+",'"+name_+"','"+city+"');";
    stmt.executeUpdate(query);

    JOptionPane.showMessageDialog(null,"Updated");

    stmt.close();
    con.close();

}
catch(Exception e) {
    JOptionPane.showMessageDialog(null,"Database Disconnected or KEY Conflict.");
}
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed

        DefaultTableModel model = (DefaultTableModel)allValues3.getModel();

        for( int i = model.getRowCount() - 1; i >= 0; i-- ) //Empty table
        {
            model.removeRow(i);
        }

        try{
            //System.out.println("Yup");
            Class.forName("com.mysql.cj.jdbc.Driver");
            //System.out.println("Yup");
            String compu="jdbc:mysql://localhost:3306/vikendu";
            Connection con = DriverManager.getConnection(compu,uid,pwd);
            // System.out.println("Yup");
            Statement stmt = con.createStatement();
            String query ="SELECT * from branches;";
            ResultSet rs = stmt.executeQuery(query);
            //System.out.println("Yup");

            while(rs.next())
            {
                String acct_no = rs.getString ("branchno");
                String name = rs.getString("branch_name");
                String phone =rs.getString("location");
                //String city = rs.getString("amount");

                model.addRow( new Object[] {acct_no, name, phone});

            }

            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Database Disconnected or KEY Conflict.");
        }
            
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
            
        int acct_no = Integer.parseInt(del_acctno3.getText());
        try{
    Class.forName("com.mysql.cj.jdbc.Driver");
    //System.out.println("Yup");
    String compu="jdbc:mysql://localhost:3306/vikendu";
    Connection con = DriverManager.getConnection(compu,uid,pwd);
   // System.out.println("Yup");
    Statement stmt = con.createStatement();
    String query = "delete from branches where branchno ="+acct_no+";";
    stmt.executeUpdate(query);

    JOptionPane.showMessageDialog(null,"Updated");

    stmt.close();
    con.close();

}
catch(Exception e) {
    JOptionPane.showMessageDialog(null,"Database Disconnected or KEY Conflict.");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        branches.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            
        JOptionPane.showMessageDialog(null,"Database Connected.");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acctno;
    private javax.swing.JTextField acctno1;
    private javax.swing.JTextField acctno2;
    private javax.swing.JTextField acctno3;
    private javax.swing.JTextField address;
    private javax.swing.JTextField address1;
    private javax.swing.JTextField address2;
    private javax.swing.JTable allValues;
    private javax.swing.JTable allValues1;
    private javax.swing.JTable allValues2;
    private javax.swing.JTable allValues3;
    private javax.swing.JFrame allvalues;
    private javax.swing.JFrame branches;
    private javax.swing.JFrame cust_detail;
    private javax.swing.JTextField del_acctno;
    private javax.swing.JTextField del_acctno1;
    private javax.swing.JTextField del_acctno2;
    private javax.swing.JTextField del_acctno3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JFrame loans;
    private javax.swing.JTextField name;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField name2;
    private javax.swing.JTextField name3;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField phone1;
    private javax.swing.JTextField phone2;
    private javax.swing.JTextField phone3;
    // End of variables declaration//GEN-END:variables
}
